# Generated by Django 5.0.3 on 2024-03-22 01:33

import subject_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='professor',
            field=models.CharField(max_length=100, validators=[subject_app.validators.validate_professor_name]),
        ),
    ]
