# Generated by Django 5.0.3 on 2024-03-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='locker_number',
            field=models.IntegerField(default=0, max_length=5),
            preserve_default=False,
        ),
    ]
