# Generated by Django 5.0.3 on 2024-03-19 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_student_locker_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='locker_number',
        ),
    ]
