# Generated by Django 5.0.3 on 2024-03-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0004_alter_student_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='locker_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='student',
            name='personal_email',
            field=models.EmailField(default='none@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='student',
            name='student_email',
            field=models.EmailField(default='none@gmail.com', max_length=254),
        ),
    ]
